-- 1. Creation of projects table.
CREATE TABLE tb_projects (
                             project_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                             name VARCHAR(255) NOT NULL,
                             description VARCHAR(500),
                             initial_date DATE,
                             final_date DATE
);

-- 2. Creation of employees table
CREATE TABLE tb_employees (
                              employee_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                              name VARCHAR(255) NOT NULL,
                              "e-mail" VARCHAR(255) NOT NULL UNIQUE, -- Lembre-se das aspas por causa do hífen
                              phone VARCHAR(50),
                              employment_type VARCHAR(50), -- Guardamos o nome do Enum como String
                              job_title VARCHAR(100),
                              department VARCHAR(100),
                              salary DECIMAL(19, 2),
                              admission_date DATE,
                              is_active BOOLEAN DEFAULT TRUE,
                              project_id BIGINT,

                              CONSTRAINT fk_employee_project FOREIGN KEY (project_id) REFERENCES tb_projects(project_id)
);