package com.github.enricofurtado.employee_management_api.Enums;

public enum JobTitle {
    // TECH
    SOFTWARE_ENGINEER, DATA_SCIENTIST, PRODUCT_OWNER, QA_ENGINEER, DEVOPS_SPECIALIST,

    // HR
    HR_MANAGER, RECRUITER, HR_BUSINESS_PARTNER,

    // SALES
    SALES_MANAGER, ACCOUNT_EXECUTIVE, SDR,

    // MARKETING
    MARKETING_DIRECTOR, SOCIAL_MEDIA_MANAGER, CONTENT_STRATEGIST,

    // FINANCE
    FINANCIAL_ANALYST, ACCOUNTANT, PAYROLL_SPECIALIST,

    // ADMIN
    OFFICE_MANAGER, ADMINISTRATIVE_ASSISTANT,

    // EXECUTIVE
    CEO, COO, PRESIDENT,

    // LEGAL
    GENERAL_COUNSEL, LEGAL_ADVISOR, COMPLIANCE_OFFICER,

    // OPERATIONS
    OPERATIONS_MANAGER, PROJECT_MANAGER, CUSTOMER_SUPPORT_LEAD;
}
